#!/bin/bash

case "$1" in
start)
   python3 /userdata/RetroFlag/RetroFlag_GPiC2_Display.py &
   echo $!>/var/run/RetroFlag_GPiC2_Display.pid
   ;;
stop)
   kill `cat /var/run/RetroFlag_GPiC2_Display.pid`
   rm /var/run/RetroFlag_GPiC2_Display.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/RetroFlag_GPiC2_Display.pid ]; then
      echo RetroFlag_GPiC2_Display is running, pid=`cat /var/run/RetroFlag_GPiC2_Display.pid`
   else
      echo RetroFlag_GPiC2_Display is NOT running
      exit 1
   fi
   ;;
esac

exit 0
